<template>
  <div>
    <scroll class="content">
      <ul>
        <li>详细信息1</li>
        <li>详细信息2</li>
        <li>详细信息3</li>
        <li>详细信息4</li>
        <li>详细信息5</li>
        <li>详细信息6</li>
        <li>详细信息7</li>
        <li>详细信息8</li>
        <li>详细信息9</li>
        <li>详细信息10</li>
        <li>详细信息11</li>
        <li>详细信息12</li>
        <li>详细信息13</li>
        <li>详细信息14</li>
        <li>详细信息15</li>
        <li>详细信息16</li>
        <li>详细信息17</li>
        <li>详细信息18</li>
        <li>详细信息19</li>
        <li>详细信息20</li>
        <li>详细信息21</li>
        <li>详细信息22</li>
        <li>详细信息23</li>
        <li>详细信息24</li>
        <li>详细信息25</li>
        <li>详细信息26</li>
        <li>详细信息27</li>
        <li>详细信息28</li>
        <li>详细信息29</li>
        <li>详细信息30</li>
        <li>详细信息31</li>
        <li>详细信息32</li>
        <li>详细信息33</li>
        <li>详细信息34</li>
        <li>详细信息35</li>
        <li>详细信息36</li>
        <li>详细信息37</li>
        <li>详细信息38</li>
        <li>详细信息39</li>
        <li>详细信息40</li>
        <li>详细信息41</li>
        <li>详细信息42</li>
        <li>详细信息43</li>
        <li>详细信息44</li>
        <li>详细信息45</li>
        <li>详细信息46</li>
        <li>详细信息47</li>
        <li>详细信息48</li>
        <li>详细信息49</li>
        <li>详细信息50</li>
        <li>详细信息51</li>
        <li>详细信息52</li>
        <li>详细信息53</li>
        <li>详细信息54</li>
        <li>详细信息55</li>
        <li>详细信息56</li>
        <li>详细信息57</li>
        <li>详细信息58</li>
        <li>详细信息59</li>
        <li>详细信息60</li>
        <li>详细信息61</li>
        <li>详细信息62</li>
        <li>详细信息63</li>
        <li>详细信息64</li>
        <li>详细信息65</li>
        <li>详细信息66</li>
        <li>详细信息67</li>
        <li>详细信息68</li>
        <li>详细信息69</li>
        <li>详细信息70</li>
        <li>详细信息71</li>
        <li>详细信息72</li>
        <li>详细信息73</li>
        <li>详细信息74</li>
        <li>详细信息75</li>
        <li>详细信息76</li>
        <li>详细信息77</li>
        <li>详细信息78</li>
        <li>详细信息79</li>
        <li>详细信息80</li>
        <li>详细信息81</li>
        <li>详细信息82</li>
        <li>详细信息83</li>
        <li>详细信息84</li>
        <li>详细信息85</li>
        <li>详细信息86</li>
        <li>详细信息87</li>
        <li>详细信息88</li>
        <li>详细信息89</li>
        <li>详细信息90</li>
        <li>详细信息91</li>
        <li>详细信息92</li>
        <li>详细信息93</li>
        <li>详细信息94</li>
        <li>详细信息95</li>
        <li>详细信息96</li>
        <li>详细信息97</li>
        <li>详细信息98</li>
        <li>详细信息99</li>
        <li>详细信息100</li>
      </ul>
    </scroll>
  </div>
</template>

<script>
  import Scroll from "components/common/scroll/Scroll";
  export default {
    name: "Profile",
    components:{
      Scroll
    }
  }
</script>

<style scoped>
  .content {
    height: 300px;
    background-color: yellowgreen;
    overflow: hidden;
  }
</style>
